# Generated by Django 5.2.8 on 2025-12-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='estatus',
            field=models.CharField(choices=[('NORMAL', 'Asistencia Normal'), ('RETARDO', 'Retardo'), ('FALTA', 'Falta'), ('JUSTIFICADA', 'Justificada por Incidencia'), ('INHABIL', 'Día Inhábil')], default='NORMAL', max_length=20),
        ),
    ]
